apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  selector:
    matchLabels:
      app: frontAngularPfe

  replicas: 1
  template:
    metadata:
      labels:
        app: frontAngularPfe
        label-key : label-value  
    spec:
      containers:
        - name: front
          image: mariemelleuch/front:2.0
          imagePullPolicy: Always
          ports:
          - containerPort: 4200
          
          ---
apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  selector:
    app: frontAngularPfe
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 31000
