apiVersion: v1
kind: Service
metadata:
  name: front-service
spec:
  type: NodePort
  selector:
    app: frontAngularPfe
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
      nodePort: 31000

